spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  application:
    name: sdz

  jwt:
    secret: sdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdz

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ongdanul1014@gmail.com"
    password: "vadcooxqnzuwgnqk"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#file:
#  upload-dir: /backend/uploads