spring:
  datasource:
    url: jdbc:mysql://34.64.176.77:5000/sdz_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sdz
    password: password

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none