server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  application:
    name: sdz

  jwt:
    secret: sdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdz

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ongdanul1014@gmail.com"
    password: "vadcooxqnzuwgnqk"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

file:
  upload-dir: "/home/kdt/backend/uploads/"