spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  application:
    name: sdz

  jwt:
    secret: sdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdzsdz

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 21d5b15dc83b412c8b80a837c215d2c2
            client-secret: pJwOSqEvQmJK3cqQ6edugNXdXtel9T81
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
          naver:
            client-name: naver
            client-id: G71zQHFmCHJ1Sw6R5kKL
            client-secret: 9dfUcWrFk5
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
          google:
            client-name: google
            client-id: 604469272709-1ka9roqt42jon1r9s94b97uvm0sk7pa0.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  targetUrl: "http://localhost:5173/"

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ongdanul1014@gmail.com"
    password: "vadcooxqnzuwgnqk"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
