spring:
  datasource:
    url: jdbc:mysql://34.64.176.77:5000/sdz_dev_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sdz
    password: password

  jpa:
    open-in-view: true          # Lazy 로딩 방지
    show-sql: true             # SQL 출력 여부
    hibernate:
      ddl-auto: update         # 테이블 구조를 자동 업데이트