spring:
  datasource:
    url: jdbc:mysql://34.64.176.77:5000/sdz_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sdz
    password: password

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 21d5b15dc83b412c8b80a837c215d2c2
            client-secret: pJwOSqEvQmJK3cqQ6edugNXdXtel9T81
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://34.64.176.77:3000/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
          naver:
            client-name: naver
            client-id: G71zQHFmCHJ1Sw6R5kKL
            client-secret: 9dfUcWrFk5
            authorization-grant-type: authorization_code
            redirect-uri: http://34.64.176.77:3000/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
          google:
            client-name: google
            client-id: 604469272709-1ka9roqt42jon1r9s94b97uvm0sk7pa0.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://34.64.176.77:3000/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  targetUrl: "http://34.64.176.77:5173/"

logging:
  level:
    root: WARN
  file:
    name: /backend/log/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss - %msg%n"
